### PR TITLE
xunit and clover report file options

### PR DESCRIPTION
**Pull request by flavien-metivier**
add option clover report file
add option xunit report file

### CODE REVIEW

**Comment by jubianchi** [comment]
up

**Comment by FlorianLB** [comment]
As usual, we can merge it now and do a refactoring later about binding between atoum and command options.

**Comment by flavien-metivier** [comment]
Build ok, previous fail due to travis timeout

**Comment by jubianchi** [comment]
@flavien-metivier please, could you add the related changelog entry ?

**Comment by flavien-metivier** [comment]
@jubianchi done

**Comment by jubianchi** [comment]
:+1: good to merge

**Comment by ekitakata** [comment]
@FlorianLB : can you merge? :)

**Comment by FlorianLB** [comment]
Thx @flavien-metivier !

**Comment by ekitakata** [comment]
Work great !

Thx @flavien-metivier, @FlorianLB, @jubianchi

**Pull request merged**
